services:
  temperature-api:
    build:
      context: ./temperature-api
    ports:
      - "8081:8081"
    restart: unless-stopped

  smart_home_db:
    image: postgres:15
    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: smarthome
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
